[package]
edition = "2021"
name = "amd64"
publish = false
version = "0.1.0"

[profile.release]
strip = true

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
bitfield-struct = "0.10.0"
num_enum = { version = "0.7.3", default-features = false }
